# Curso basasico de Nunpy

In [159]:
import numpy as np

In [160]:
lista = [1,2,3,4,5]
matriz = [[1,2,3],[4,5,6],[7,8,9]]

### Funcion array de Numpy para crear vectores, matrices, tensores.

In [161]:
arrayNumpy = np.array(lista)
matrizNumpy = np.array(matriz)

arrayNumpy es un objeto de clase array de numpy.

In [162]:
arrayNumpy

array([1, 2, 3, 4, 5])

In [163]:
type(arrayNumpy)

numpy.ndarray

Lo mismo ocurre con matrizNumpay.

In [164]:
matrizNumpy

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

In [165]:
type(matrizNumpy)

numpy.ndarray

### Trabajo con indexación.

In [166]:
arrayNumpy

array([1, 2, 3, 4, 5])

In [167]:
arrayNumpy[1]

2

In [168]:
arrayNumpy[2]

3

Puedo realizar operaciones a base al valor almacenado en cada indice.

In [169]:
arrayNumpy[1] + arrayNumpy[2]

5

Aplicable tambien a matrices.

In [170]:
matrizNumpy[1]

array([4, 5, 6])

In [171]:
matrizNumpy[2]

array([7, 8, 9])

Sumara cada una de las posiciones con aquella que concuerde en posicion en la otra lista de la matriz, las matrices deben tener la misma longitud.

In [172]:
matrizNumpy[2] + matrizNumpy[1]

array([11, 13, 15])

In [173]:
matrizNumpy[0] + matrizNumpy[1] + matrizNumpy[2]

array([12, 15, 18])

 Sintaxis Numpy para acceder a coordenadas dentro de la matriz, no es necesario encerrar cada posicion en entre corchetes, solo falta un par y separar las posiciones con una coma.

In [174]:
matrizNumpy

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

In [175]:
matrizNumpy[0,2]

3

Sumamos la posion 0 de la lista que esta en posision 0 dentro de la matriz, y la posision 0 de la lista que esta en posision 1 de la matriz.
1+4

In [176]:
matrizNumpy[0,0] + matrizNumpy[1,0]

5

##### Puedo trabajar con slice.

In [177]:
arrayNumpy

array([1, 2, 3, 4, 5])

Recarodar que en terminos de slice cuando definimos el limite del slace no es considerado, en el siguiente caso devuelve todo el array por que este posee solo 4 posiciones a partir de cero.

In [178]:
arrayNumpy[0:5]

array([1, 2, 3, 4, 5])

In [179]:
arrayNumpy[1:4]

array([2, 3, 4])

Slice abreviado devuelve desde el inicio hasta la posicion 5

In [180]:
arrayNumpy[:5]

array([1, 2, 3, 4, 5])

In [181]:
arrayNumpy[:4]

array([1, 2, 3, 4])

Metodo abreviado, devuvleve todo a partir de la siguiente posicion.

In [182]:
arrayNumpy[0:]

array([1, 2, 3, 4, 5])

In [183]:
arrayNumpy[3:]

array([4, 5])

Slice abreviado para devolver todo el arreglo.

In [184]:
arrayNumpy[::]

array([1, 2, 3, 4, 5])

Tambien podemos definir un condicion de salto entre los datos, por ejemplo traer todo pero cada tres posociones.

In [185]:
arrayNumpy[::3]

array([1, 4])

Tambien permite trabajar con indices negativos.

In [186]:
arrayNumpy[-3:]

array([3, 4, 5])

Tambien aplicable a matrices,pido devuelva las filas desde la posicion 1 a la ultima, y de las columnas solo desde la posicion 0 a 1

In [187]:
matrizNumpy[1:,0:2]

array([[4, 5],
       [7, 8]])

### Tipos de datos

In [188]:
arr = np.array([1,2,3,4])

dtype indica el tipo de datos de los que se compone el array

In [189]:
arr.dtype

dtype('int32')

Puedo modificar el tipo, por ejemplos las redes neuronales se llevan mejor con float64.

In [190]:
arr2 = np.array([1,2,3,4], dtype='float64') 

Podemos observer que convierte los numeros enteros dentro del array a flotante

In [191]:
arr2 

array([1., 2., 3., 4.])

Otra forma de convertir el tipo de dato.

In [192]:
arr3 = np.array([1,2,3,4])

In [193]:
arr3

array([1, 2, 3, 4])

Trasnformo directamente utilizando las funciones de numpy.

In [194]:
arr3 = arr3.astype(np.float64)

In [195]:
arr3 

array([1., 2., 3., 4.])

In [196]:
arr4 = np.array([0,1,2,3,4])

Convierte los datos en booleanos

In [197]:
arr4 = arr4.astype(np.bool_)

In [198]:
arr4

array([False,  True,  True,  True,  True])

Convierte los datos en cadenas de texto.

In [199]:

arr5 = np.array([0,1,2,3,4])

In [200]:
arr5 = arr5.astype(np.str_)

In [201]:
arr5

array(['0', '1', '2', '3', '4'], dtype='<U11')

In [202]:
arr6 = np.array([0,1,2,3,4])

In [203]:
arr6 = arr6.astype(np.string_)

In [204]:
arr6

array([b'0', b'1', b'2', b'3', b'4'], dtype='|S11')

* En NumPy, cuando ves una cadena de texto precedida por una 'b', como en b'0', significa que la cadena es de tipo bytes en lugar de una cadena de texto Unicode. Estas cadenas se denominan "bytestrings" o "strings de bytes" y son un tipo de dato binario en lugar de una cadena de texto.

In [205]:
arr6 = arr6.astype(np.int8) 

In [206]:
arr6

array([0, 1, 2, 3, 4], dtype=int8)

* Ojo no podria comvertir una palabra a un numero, solo funciona si el caracter es un digito

### Dimesiones

* scalar: dim = 0 Un solo dato o valor

* vector: dim = 1 Listas de Python

* matriz: dim = 2 Hoja de cálculo 

* tensor: dim >= 3 Series de tiempo o Imágenes

Escalar

In [207]:
scalar = np.array(21)

In [208]:
scalar

array(21)

El escalar posee 0 dimesiones

In [209]:
'numero de dimensiones: ', scalar.ndim

('numero de dimensiones: ', 0)

Vector

In [210]:
vector = np.array([1,2,3,4])

In [211]:
vector

array([1, 2, 3, 4])

Un vector posee una dimension

In [212]:
'numero de dimensiones: ', vector.ndim

('numero de dimensiones: ', 1)

Matriz

In [213]:
matriz = np.array([[1,2,3,4], [5,6,7,8]])

In [214]:
matriz

array([[1, 2, 3, 4],
       [5, 6, 7, 8]])

In [215]:
'numero de dimensiones: ', matriz.ndim

('numero de dimensiones: ', 2)

Tensor, se considera tal desde 3 a n dimesiones

In [216]:
tensor = np.array([[[1,2,3,4], [5,6,7,8]],[[1,2,3,4], [5,6,7,8]]]) 

In [217]:
tensor

array([[[1, 2, 3, 4],
        [5, 6, 7, 8]],

       [[1, 2, 3, 4],
        [5, 6, 7, 8]]])

In [218]:
'numero de dimensiones: ', tensor.ndim

('numero de dimensiones: ', 3)

* Agregar o quitar dimesiones

Agregar dimesiones

In [219]:
vector2 = np.array([1,2,3,4,5], ndmin=10)

ndim = n Automaticamente creara las dimesione requeridas

In [220]:
vector2

array([[[[[[[[[[1, 2, 3, 4, 5]]]]]]]]]])

In [221]:
'numero de dimensiones: ', vector2.ndim

('numero de dimensiones: ', 10)

In [222]:
expand = np.expand_dims(np.array([1,2,3,4]), axis=0) 

El axis 0 es el eje vertical y representa las filas

In [223]:
expand

array([[1, 2, 3, 4]])

In [224]:
expand = np.expand_dims(np.array([1,2,3,4]), axis=1) 

El axis 1 es el eje horizontal y representa las columnas

In [225]:
expand

array([[1],
       [2],
       [3],
       [4]])

* Restar dimesiones.

In [226]:
vector2, vector2.ndim

(array([[[[[[[[[[1, 2, 3, 4, 5]]]]]]]]]]), 10)

squeeze Elmina las dimesiones que, segun calcula numpy, no se estan utilizando.

In [227]:
vector3 = vector2.squeeze()

In [228]:
vector3, vector3.ndim

(array([1, 2, 3, 4, 5]), 1)

### Creacion de arrays predeterminados

* Crear un array en un rango de numeros predeteminados.

In [229]:
arr = np.arange(1,10) 

Al igual que range de py, obvia el numero final designado para el rango.

In [230]:
arr

array([1, 2, 3, 4, 5, 6, 7, 8, 9])

In [231]:
arr2 = np.arange(0,20,2)

Se puede dar salto entre numero, en este caso de 2 en 2

In [232]:
arr2

array([ 0,  2,  4,  6,  8, 10, 12, 14, 16, 18])

La funcion zeros crea un array de n espacios por filas y llena los espacios con 0 flotantes, para despues trabajar y llenarlas con otros datos.

In [233]:
arr3 = np.zeros(3)

In [234]:
arr3 

array([0., 0., 0.])

Tambien puedo aplicarlo para crear matrices, indicando el numero de columnas y filas. Se le debe entregar las dimesiones en formato tupla.

In [235]:
arr4 = np.zeros((10,10)) 

In [236]:
arr4

array([[0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 0.]])

In [237]:
arr5 = np.zeros((3,3,3)) 

In [238]:
arr5

array([[[0., 0., 0.],
        [0., 0., 0.],
        [0., 0., 0.]],

       [[0., 0., 0.],
        [0., 0., 0.],
        [0., 0., 0.]],

       [[0., 0., 0.],
        [0., 0., 0.],
        [0., 0., 0.]]])

La funcion ones hace lo mismo que zeros pero aplicando 1 flotante.

In [239]:
arr6 = np.ones((3,3)) 

In [240]:
arr6

array([[1., 1., 1.],
       [1., 1., 1.],
       [1., 1., 1.]])

linspace crea un vector con un rango desde (numero inicio, numero final, cantidad de datos a generar) 

In [241]:
arr7 = np.linspace(0,10,20)

In [242]:
arr7

array([ 0.        ,  0.52631579,  1.05263158,  1.57894737,  2.10526316,
        2.63157895,  3.15789474,  3.68421053,  4.21052632,  4.73684211,
        5.26315789,  5.78947368,  6.31578947,  6.84210526,  7.36842105,
        7.89473684,  8.42105263,  8.94736842,  9.47368421, 10.        ])

eye devuelve una matriz con la digonal en 1 y el resto en ceros.

In [243]:
arr8 = np.eye(4) 

In [244]:
arr8

array([[1., 0., 0., 0.],
       [0., 1., 0., 0.],
       [0., 0., 1., 0.],
       [0., 0., 0., 1.]])

np.random.rand sin argumentos devuelve un numero aleatorio entre 0 y 1.

In [245]:
arr9 = np.random.rand() 

In [246]:
arr9 

0.6938744607718632

random.rand con un argumento devuelve un vector con 4 numeros aleatorios entre 0 y 1, devuelve 4 columnas.

In [247]:
arr10 = np.random.rand(4)

In [248]:
arr10 

array([0.01538143, 0.59761553, 0.12658501, 0.98895656])

Tambien puede generar  una matriz de n x n, cada fila tendra n datos(columnas) con numeros entre 0 y 1 

In [249]:
arr11 = np.random.rand(4,4) 

In [250]:
arr11

array([[0.34469797, 0.73522912, 0.29872708, 0.39099785],
       [0.48547114, 0.34895394, 0.31143408, 0.27352964],
       [0.1265871 , 0.78633777, 0.89620675, 0.96351013],
       [0.40972894, 0.46799611, 0.69764681, 0.43045188]])

np.random.randint aplica los numeros random a una estrucutra matrcial n x n.

In [251]:
arr13 = np.random.randint(1,10, (5,5))

In [252]:
arr13 

array([[8, 3, 7, 7, 3],
       [2, 7, 9, 5, 7],
       [4, 3, 8, 7, 1],
       [2, 3, 9, 1, 6],
       [4, 5, 6, 9, 1]])

In [253]:
arr13 = np.random.randint(1,10, (2,3,3,5))

* Nota en un esquema de dimesiones de matriz (n,n,n) siempre el ultimo numero representa las columnas.

In [254]:
arr13

array([[[[3, 1, 9, 4, 3],
         [6, 7, 9, 8, 4],
         [2, 2, 9, 8, 3]],

        [[8, 8, 9, 3, 1],
         [8, 1, 7, 8, 7],
         [5, 3, 2, 1, 9]],

        [[6, 4, 1, 7, 7],
         [8, 7, 8, 6, 1],
         [5, 1, 4, 8, 3]]],


       [[[7, 7, 2, 8, 2],
         [9, 6, 9, 4, 4],
         [7, 6, 4, 8, 3]],

        [[2, 3, 3, 5, 8],
         [2, 3, 3, 3, 3],
         [5, 7, 1, 8, 2]],

        [[5, 7, 5, 3, 8],
         [8, 2, 6, 3, 7],
         [3, 6, 9, 4, 1]]]])

### Redimension shape y reshaper

In [255]:
arr = np.random.randint(1,10,(3,2))

In [256]:
arr

array([[7, 9],
       [9, 8],
       [7, 6]])

In [257]:
arr.ndim

2

shape devuelve el numero de dimensiones de objeto en formato tupla (n,n).

In [258]:
arr.shape

(3, 2)

reshape redimesiona la matriz, de acuerdo a las dimeisones entregada por parametros.

In [259]:
arr

array([[7, 9],
       [9, 8],
       [7, 6]])

In [260]:
arr.reshape(1,6)

array([[7, 9, 9, 8, 7, 6]])

Puede hacer el reshape, siempre y cuando calcen la cantidad de datos previa en el numero de columnas y filas reasignados, su no tiene con que llenar lanza una excepcion.

In [261]:
arr.reshape(2,3)

array([[7, 9, 9],
       [8, 7, 6]])

In [262]:
arr.reshape(6,1)

array([[7],
       [9],
       [9],
       [8],
       [7],
       [6]])

Otra sintaxis para reshape

In [263]:
arr15 = np.reshape(arr,(1,6))

In [264]:
arr15

array([[7, 9, 9, 8, 7, 6]])

Parametros de ordenamiento

* 'C' Ordena segun lenguaje C en este caso por filas.

In [265]:
arr3 = np.reshape(arr,(1,6),'C')

In [266]:
arr3

array([[7, 9, 9, 8, 7, 6]])

* 'F' ! Ordena segun el lenguaje fortran, es este caso por columnas.

In [267]:
arr4 = np.reshape(arr,(1,6),'F')

In [268]:
arr4

array([[7, 9, 7, 9, 8, 6]])

* 'A' Ordena segun la optimizacion para mi laptorm, en este caso en C.

In [269]:
arr5 = np.reshape(arr,(1,6), 'A')

In [270]:
arr5

array([[7, 9, 9, 8, 7, 6]])

* por defecto se ordena en C

### Funciones principales de numpy

In [271]:
arr = np.random.randint(1,20,10) #Vector de 10 columnas con Numeros entre 1 y 20.

In [272]:
arr

array([ 4,  5, 14,  5, 17, 12,  3,  3,  8, 12])

In [273]:
matriz = arr.reshape(2,5) #Redimencion a matriz de 2 filas de 5 columnas cada una.

In [274]:
matriz

array([[ 4,  5, 14,  5, 17],
       [12,  3,  3,  8, 12]])

* Obtener el numero máximo dentro de una estructura

In [275]:
maximo = arr.max()

In [276]:
maximo

17

In [277]:
max_matriz = matriz.max()

In [278]:
max_matriz

17

* Devuelve el elemnto maximo de cada columna Axis 0

In [279]:
maxMatrizColumnas = matriz.max(0)

In [280]:
maxMatrizColumnas

array([12,  5, 14,  8, 17])

* Devuelve el elemnto maximo de cada fila Axis 1

In [281]:
maxMatrizFilas = matriz.max(1)

In [282]:
maxMatrizFilas

array([17, 12])

* argmax() devuelve el indice donde se encuentra el numero mayor.

In [283]:
arr.argmax()

4

In [284]:
matriz.argmax(0)

array([1, 0, 0, 1, 0], dtype=int64)

In [285]:
matriz.argmax(1)

array([4, 0], dtype=int64)

* Obtener el numero minimo dentro de una estructura.

In [286]:
arr.min()

3

In [287]:
matriz.min()

3

In [288]:
matriz.min(0)

array([ 4,  3,  3,  5, 12])

In [289]:
matriz.min(1)

array([4, 3])

* argmin() devuelve el indice donde se encuentra el numero minimo dentro del objeto.

In [290]:
arr.argmin()

6

In [291]:
matriz.argmin(0)

array([0, 1, 1, 0, 1], dtype=int64)

In [292]:
matriz.argmin(1)

array([0, 1], dtype=int64)

* Punto a punto, devuelve la distancia entre el numero menor y el mayor.

In [293]:
lista = np.array([1,2,3,4,5])

In [294]:
lista.ptp()

4

* PTP en matriz total.

In [295]:
matriz.ptp()

14

*  Distancia punto a punto por columnas.

In [296]:
matriz.ptp(0)

array([ 8,  2, 11,  3,  5])

*  Distancia punto a punto por filas

In [297]:
matriz.ptp(1)

array([13,  9])

* Percentil Valor en referencia un grupo de 100, considetando que percentil 50 es justo la mitad, coincideinedo con la mediana.

In [298]:
np.percentile(lista, 64)

3.56

In [299]:
array = np.arange(1,101)

In [300]:
np.percentile(array, 0)

1.0

* Median() Devuelve la mediana de la lista, que es igual al percentil 50.

In [301]:
ul = np.array([8,6,2,9,1,5])

In [302]:
np.median(ul)

5.5

* Median en matriz.

In [303]:
np.median(matriz)

6.5

In [304]:
np.median(matriz, 0)

array([ 8. ,  4. ,  8.5,  6.5, 14.5])

In [305]:
np.median(matriz, 1)

array([5., 8.])

* sort() ordena la lista de menor a mayor.

In [306]:
ul.sort() 

In [307]:
ul

array([1, 2, 5, 6, 8, 9])

* Desviasion estandar

In [308]:
np.std(arr)

4.817675788178362

* Varianza

In [309]:
np.var(arr)

23.21

* Obtener promedio

In [310]:
np.mean(arr)

8.3

* Concatenar vectores y matrices.

In [311]:
a = np.array([[1,2],[3,4]])
b = np.array([[5,6],[7,8]])

In [312]:
np.concatenate((a,b), axis=0)

array([[1, 2],
       [3, 4],
       [5, 6],
       [7, 8]])

* Si concatenamos por eje 1 debemos procurar tener la misma dimensiones en ambos array, de no ser el caso debemos expandir donde sea necesario.

In [313]:
np.concatenate((a,b), axis=1) 

array([[1, 2, 5, 6],
       [3, 4, 7, 8]])

* La transpuerta invierte las dimesiones

In [314]:
x = np.array([[1,2,3],[4,5,6]])

In [315]:
x

array([[1, 2, 3],
       [4, 5, 6]])

In [316]:
x.T

array([[1, 4],
       [2, 5],
       [3, 6]])

* copy() Crea un copia del array para no modificar el original, lo clasico.

In [317]:
arr = np.arange(1,11)

In [318]:
arr

array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10])

In [319]:
arr2 = np.copy(arr)

In [320]:
arr2

array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10])

In [321]:
arr2[:] = 0 #Covertimos todos los numeros de arr2 en 0.

In [322]:
arr

array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10])

In [323]:
arr2

array([0, 0, 0, 0, 0, 0, 0, 0, 0, 0])

### Condicionales

In [329]:
arr = np.linspace(1,20,20, dtype='int8')

In [330]:
arr

array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16, 17,
       18, 19, 20], dtype=int8)

* Devuelve los mayores a 5.

In [331]:
arr[arr > 5]

array([ 6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16, 17, 18, 19, 20],
      dtype=int8)

* Devuelve el rango entre los mayores a 5 y menores a 9.

In [332]:
arr[(arr > 5) & (arr < 9)]

array([6, 7, 8], dtype=int8)

* Reasigna a valor especificado todos los numeros que cumplen la condicion.

In [338]:
arr[arr > 5] = 99

In [339]:
arr

array([ 1,  2,  3,  4,  5, 99, 99, 99, 99, 99, 99, 99, 99, 99, 99, 99, 99,
       99, 99, 99], dtype=int8)

In [340]:
arr[arr == 99]

array([99, 99, 99, 99, 99, 99, 99, 99, 99, 99, 99, 99, 99, 99, 99],
      dtype=int8)

In [342]:
arr[arr == 0]

array([], dtype=int8)

In [345]:
arr[arr != 0]

array([ 2,  3,  4,  5, 99, 99, 99, 99, 99, 99, 99, 99, 99, 99, 99, 99, 99,
       99, 99], dtype=int8)

In [346]:
arr[arr != 99]

array([1, 2, 3, 4, 5], dtype=int8)

* Si pasamos directamente la condicion devolvera un array indicando con true o false los elementos de la lista segun la condicion.

In [344]:
arr != 99

array([ True,  True,  True,  True,  True, False, False, False, False,
       False, False, False, False, False, False, False, False, False,
       False, False])

### Operaciones

In [347]:
arr = np.arange(0,10)

In [348]:
arr2 =np.copy(arr)

In [350]:
arr2

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

* Aplica la operacion a cada uno de los elementos del array

In [349]:
arr2 * 2

array([ 0,  2,  4,  6,  8, 10, 12, 14, 16, 18])

In [351]:
arr2 + 2

array([ 2,  3,  4,  5,  6,  7,  8,  9, 10, 11])

* Division por cero Arroja un warning de zero division sin embargo sigue aplicando la operacion al resto de los elemntos.


In [353]:
1 / arr2

C:\Users\alanm\AppData\Local\Temp\ipykernel_24016\3854864060.py:1: RuntimeWarning: divide by zero encountered in divide
  1 / arr2


array([       inf, 1.        , 0.5       , 0.33333333, 0.25      ,
       0.2       , 0.16666667, 0.14285714, 0.125     , 0.11111111])

* Operacons entre arrays realizara la operacion entre los elementos de cada posicion primer array con los elementos en las mismas posiciones del segundo array. Para operar, ambas estrucura deben tener las mismas filas y columnas.

In [354]:
arr + arr2

array([ 0,  2,  4,  6,  8, 10, 12, 14, 16, 18])

In [355]:
arr - arr2

array([0, 0, 0, 0, 0, 0, 0, 0, 0, 0])

In [356]:
arr * arr2

array([ 0,  1,  4,  9, 16, 25, 36, 49, 64, 81])

In [358]:
arr / arr2

C:\Users\alanm\AppData\Local\Temp\ipykernel_24016\1444868932.py:1: RuntimeWarning: invalid value encountered in divide
  arr / arr2


array([nan,  1.,  1.,  1.,  1.,  1.,  1.,  1.,  1.,  1.])

In [359]:
lir = np.array([1,2,3])

* Operaciones con matrices

In [366]:
matriz1 = arr.reshape(2,5)

In [367]:
matriz2 = matriz1.copy()

In [368]:
matriz1 + matriz2

array([[ 0,  2,  4,  6,  8],
       [10, 12, 14, 16, 18]])

In [369]:
matriz1 - matriz2

array([[0, 0, 0, 0, 0],
       [0, 0, 0, 0, 0]])

In [370]:
matriz1 * matriz2

array([[ 0,  1,  4,  9, 16],
       [25, 36, 49, 64, 81]])

In [371]:
matriz1 / matriz2

C:\Users\alanm\AppData\Local\Temp\ipykernel_24016\3302158648.py:1: RuntimeWarning: invalid value encountered in divide
  matriz1 / matriz2


array([[nan,  1.,  1.,  1.,  1.],
       [ 1.,  1.,  1.,  1.,  1.]])